//
//  StructuurVariabelen.swift
//  Fuelcounter
//
//  Created by Nelson on 06/06/2020.
//  Copyright © 2020 Nelson. All rights reserved.
//

import Foundation

class Transport{
    var ID: Int // autogegenereerd maar verplicht
    var naam: String // verplicht
    var km: Double //niet verplicht en boven 999 999 niet interessant dus range van 0 tot 999 999
    var gemverbruik:Double //wordt automatisch berkend
    var bouwjaar:Int //niet verplicht
    var type:Typevervoer // verplicht
    var merk:String // niet verplicht
    var model:String // niet verplicht
  //  var urlimage:String // niet verplicht een extra voor als er genoeg tijd is.
    init(naam: String,km: Double , bouwjaar : Int , type:Typevervoer , merk:String,model:String){
        self.ID = 0 //moet nog autogenerated worden
        self.naam = naam
        self.km = km
        self.bouwjaar = bouwjaar
        self.type = type
        self.merk = merk
        self.model = model
        self.gemverbruik = 0
    }
    
    init(naam: String,km: Double , type:Typevervoer , merk:String,model:String){
        self.ID = 0 //moet nog autogenerated worden
        self.naam = naam
        self.km = km
        self.bouwjaar = 0
        self.type = type
        self.merk = merk
        self.model = model
        self.gemverbruik = 0
    }
}
enum Typevervoer{
    case electrisch,bezine,disel,lpg,andere // type transport middelen
}

class meeting {
    var ID:Int
    var datum: Date // datum van de meeting verplicht
    var IDvoertuig : Int //verplicht verwijst naar voertuig
    var km:Double // verplicht aantal km
    var verbruikte:Double // verplicht geeft aantal verbuikte energie weer
    
    init(datum: Date, IDvoertuig : Int , km:Double , verbruikte:Double){
           self.ID = 0
           self.datum = datum
           self.IDvoertuig = IDvoertuig
           self.km = km
           self.verbruikte = verbruikte
       }
}
